name: horas_v1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.0
  flutterfire_cli: ^1.1.0
  cloud_firestore: ^5.6.4
  firebase_auth: ^5.5.0
  firebase_messaging: ^15.2.3
  google_sign_in: ^6.3.0
  mask_text_input_formatter: ^2.8.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
